const toggle=document.querySelector('.menu-toggle'),menu=document.querySelector('#mobile-menu');
function closeMenu(){if(!toggle||!menu)return;toggle.setAttribute('aria-expanded','false');menu.hidden=true;document.body.classList.remove('menu-open');}
toggle?.addEventListener('click',()=>{const open=toggle.getAttribute('aria-expanded')!=='true';toggle.setAttribute('aria-expanded',String(open));menu.hidden=!open;document.body.classList.toggle('menu-open',open);});
menu?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&toggle?.getAttribute('aria-expanded')==='true'){closeMenu();toggle.focus();}});
window.matchMedia('(min-width:761px)').addEventListener('change',e=>{if(e.matches)closeMenu();});
const planSelect=document.querySelector('#application-plan'),validPlans=['Help me choose','Full Coaching','Nutrition','Training','Contest Prep'];
document.querySelectorAll('[data-plan]').forEach(a=>a.addEventListener('click',()=>{if(planSelect)planSelect.value=a.dataset.plan;}));
const incomingPlan=new URLSearchParams(location.search).get('plan');if(planSelect&&validPlans.includes(incomingPlan))planSelect.value=incomingPlan;
const sticky=document.querySelector('.mobile-sticky'),hero=document.querySelector('.hero'),apply=document.querySelector('#apply');let pastHero=false,atApply=false;
function updateSticky(){sticky?.classList.toggle('visible',pastHero&&!atApply);}
if('IntersectionObserver'in window){if(hero)new IntersectionObserver(([e])=>{pastHero=!e.isIntersecting&&e.boundingClientRect.top<0;updateSticky();}).observe(hero);if(apply)new IntersectionObserver(([e])=>{atApply=e.isIntersecting;updateSticky();},{rootMargin:'0px 0px 150px 0px'}).observe(apply);if(!window.matchMedia('(prefers-reduced-motion:reduce)').matches){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('reveal-in');observer.unobserve(e.target);}}),{threshold:.15});document.querySelectorAll('.method-row,.process-grid article,.section-heading').forEach(el=>observer.observe(el));}}
if(new URLSearchParams(location.search).get('gate')==='onboarding-requires-payment'){const notice=document.createElement('p');notice.className='gate-notice';notice.textContent='Client onboarding follows enrollment. Choose your coaching plan below, or apply for a free discovery call.';document.querySelector('main')?.prepend(notice);}
const form=document.querySelector('#application-form');
form?.addEventListener('submit',async e=>{e.preventDefault();if(!form.reportValidity())return;const button=form.querySelector('button[type=submit]'),status=document.querySelector('#form-status');if(button.disabled)return;button.disabled=true;button.textContent='Sending your application…';status.textContent='';status.className='';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),15000);try{const response=await fetch('/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(new FormData(form)).toString(),signal:controller.signal});if(!response.ok)throw new Error('Application not accepted');location.assign('/thank-you');}catch{status.className='error';status.textContent='Your application could not be confirmed. Please try again or email ';const link=document.createElement('a');link.href='mailto:jonmurr.fit@gmail.com';link.textContent='jonmurr.fit@gmail.com';status.append(link,'. Your answers are still here.');button.disabled=false;button.innerHTML='Send my application <span aria-hidden="true">↗</span>';}finally{clearTimeout(timer);}});
